# Generated by Django 4.2.3 on 2023-07-31 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer_engine', '0011_alter_dishes_aaf_adj_prot_alter_dishes_calcium_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dishes',
            name='quantity',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
