# Generated by Django 4.2.3 on 2023-08-06 01:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer_engine', '0015_customer'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomerStatus',
        ),
    ]
