# Generated by Django 4.2.3 on 2023-09-03 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer_engine', '0037_dishes'),
    ]

    operations = [
        migrations.RenameField(
            model_name='breakfast',
            old_name='usable_cals',
            new_name='aa_factor',
        ),
        migrations.RenameField(
            model_name='dinner',
            old_name='usable_cals',
            new_name='aa_factor',
        ),
        migrations.RenameField(
            model_name='lunch',
            old_name='usable_cals',
            new_name='aa_factor',
        ),
        migrations.RenameField(
            model_name='snacks',
            old_name='usable_cals',
            new_name='aa_factor',
        ),
        migrations.AddField(
            model_name='breakfast',
            name='cals',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='breakfast',
            name='glucose',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='breakfast',
            name='ingredients',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='breakfast',
            name='pral',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='breakfast',
            name='veg_nonveg_egg',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='dinner',
            name='cals',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='dinner',
            name='glucose',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='dinner',
            name='ingredients',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='dinner',
            name='pral',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='dinner',
            name='veg_nonveg_egg',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='lunch',
            name='cals',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='lunch',
            name='glucose',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='lunch',
            name='ingredients',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='lunch',
            name='pral',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='lunch',
            name='veg_nonveg_egg',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='snacks',
            name='cals',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='snacks',
            name='glucose',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='snacks',
            name='ingredients',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='snacks',
            name='pral',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='snacks',
            name='veg_nonveg_egg',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
