# Generated by Django 4.2.3 on 2023-08-26 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backoffice_engine', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminuser',
            name='image_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
