# Generated by Django 4.2.3 on 2023-08-26 03:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backoffice_engine', '0002_adminuser_image_url'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AdminUser',
        ),
    ]
