# Generated by Django 4.2.3 on 2023-07-29 11:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer_engine', '0006_rename_status_customer_customer_type'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Customer',
        ),
    ]
