# Generated by Django 4.2.3 on 2023-08-03 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer_engine', '0012_alter_dishes_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='age',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='contact_number',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='date',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='image',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='location',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='medical_condition',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='name',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='tall',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='weight',
        ),
        migrations.AlterField(
            model_name='customer',
            name='customer_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
