# Generated by Django 4.2.3 on 2023-08-03 03:27

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('customer_engine', '0014_remove_customerstatus_customer_delete_customer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_type', models.CharField(blank=True, max_length=100, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(blank=True, max_length=100, null=True)),
                ('gender', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=500)),
                ('contact_number', models.CharField(max_length=15)),
                ('email', models.CharField(max_length=100)),
                ('date_of_birth', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('height', models.DecimalField(decimal_places=1, max_digits=3)),
                ('weight', models.DecimalField(decimal_places=1, max_digits=5)),
                ('health_issue', models.CharField(max_length=500)),
                ('other_issue', models.CharField(max_length=500)),
                ('any_medication', models.CharField(max_length=500)),
                ('veg_nonveg', models.CharField(max_length=500)),
                ('profession', models.CharField(max_length=200)),
                ('help', models.CharField(max_length=500)),
                ('date', models.DateField(default=django.utils.timezone.now)),
            ],
        ),
    ]
