# Generated by Django 4.2.3 on 2023-08-11 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer_engine', '0019_userotp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='height',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='weight',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
