# Generated by Django 4.2.3 on 2023-08-13 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer_engine', '0025_alter_customer_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='image',
        ),
        migrations.AddField(
            model_name='customer',
            name='image_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
