# Generated by Django 4.2.3 on 2023-08-16 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer_engine', '0026_remove_customer_image_customer_image_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='health_issue',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='other_issue',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
