# Generated by Django 4.2.3 on 2023-09-09 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer_engine', '0040_calorycount_dish_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calorycount',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
