# Generated by Django 4.2.3 on 2023-09-13 07:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer_engine', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dailyrecipe',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='dailyrecipe',
            name='updated_at',
        ),
    ]
