# Generated by Django 4.2.3 on 2023-09-12 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer_engine', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailysnacks',
            name='meal_type',
            field=models.CharField(choices=[('breakfast', 'Breakfast'), ('lunch', 'Lunch'), ('dinner', 'Dinner'), ('snacks', 'Snacks')], max_length=10),
        ),
    ]
