# Generated by Django 4.2.3 on 2023-09-12 14:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer_engine', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='user',
        ),
    ]
