# Generated by Django 4.2.3 on 2023-09-11 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer_engine', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='otp',
            field=models.IntegerField(),
        ),
    ]
