# Generated by Django 4.2.3 on 2023-09-13 13:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer_engine', '0002_remove_dailyrecipe_created_at_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usersnacks',
            old_name='dailySnacks',
            new_name='dish_ids',
        ),
    ]
