# Generated by Django 4.2.3 on 2023-07-29 04:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer_engine', '0002_alter_customer_date'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Customer',
        ),
    ]
