# Generated by Django 4.2.3 on 2023-09-12 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer_engine', '0002_alter_dailysnacks_meal_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailysnacks',
            name='meal_type',
            field=models.CharField(choices=[('breakfast', 'Breakfast'), ('lunch', 'Lunch'), ('dinner', 'Dinner'), ('evening_snacks', 'Evening Snacks')], max_length=15),
        ),
    ]
