# Generated by Django 4.2.3 on 2023-07-29 10:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer_engine', '0005_remove_customer_activity_level_remove_customer_email_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='status',
            new_name='customer_type',
        ),
    ]
