# Generated by Django 4.2.3 on 2023-07-31 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer_engine', '0008_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dishes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('food', models.CharField(max_length=200)),
                ('quantity', models.IntegerField()),
                ('pral', models.IntegerField()),
                ('glycemicload', models.IntegerField()),
                ('oil', models.IntegerField()),
                ('calories', models.IntegerField()),
                ('aaf_adj_prot', models.IntegerField()),
                ('carbohydtrates', models.IntegerField()),
                ('total_fat', models.IntegerField()),
                ('tdf', models.IntegerField()),
                ('sodium', models.IntegerField()),
                ('potassium', models.IntegerField()),
                ('phasphorous', models.IntegerField()),
                ('calcium', models.IntegerField()),
                ('magnecium', models.IntegerField()),
                ('total_eaa', models.IntegerField()),
                ('lysine', models.IntegerField()),
                ('gross_protine', models.IntegerField()),
                ('free_suger', models.IntegerField()),
            ],
        ),
    ]
