# Generated by Django 4.2.3 on 2023-07-31 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer_engine', '0009_dishes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dishes',
            name='aaf_adj_prot',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='dishes',
            name='calcium',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='dishes',
            name='calories',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='dishes',
            name='carbohydtrates',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='dishes',
            name='free_suger',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='dishes',
            name='glycemicload',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='dishes',
            name='gross_protine',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='dishes',
            name='lysine',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='dishes',
            name='magnecium',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='dishes',
            name='oil',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='dishes',
            name='phasphorous',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='dishes',
            name='potassium',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='dishes',
            name='pral',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='dishes',
            name='quantity',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='dishes',
            name='sodium',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='dishes',
            name='tdf',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='dishes',
            name='total_eaa',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='dishes',
            name='total_fat',
            field=models.FloatField(),
        ),
    ]
