# Generated by Django 4.2.3 on 2023-08-03 03:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer_engine', '0013_remove_customer_age_remove_customer_contact_number_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customerstatus',
            name='customer',
        ),
        migrations.DeleteModel(
            name='Customer',
        ),
    ]
