# Generated by Django 4.2.3 on 2023-08-20 05:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customer_engine', '0027_alter_customer_health_issue_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddRecipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=1000)),
                ('sub_name', models.CharField(max_length=1000)),
                ('quantity', models.FloatField(null=True)),
                ('quantity_help', models.FloatField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='AddIngridient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ingridient_name', models.CharField(max_length=1000)),
                ('ingridient_quantity', models.FloatField(null=True)),
                ('protein', models.FloatField(null=True)),
                ('calories', models.FloatField(null=True)),
                ('fat', models.FloatField(null=True)),
                ('carps', models.FloatField(null=True)),
                ('sugars', models.FloatField(null=True)),
                ('sodium', models.FloatField(null=True)),
                ('fiber', models.FloatField(null=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer_engine.addrecipe')),
            ],
        ),
    ]
