# Generated by Django 4.2.3 on 2023-08-20 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer_engine', '0028_addrecipe_addingridient'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addingridient',
            name='calories',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='addingridient',
            name='carps',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='addingridient',
            name='fat',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='addingridient',
            name='fiber',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='addingridient',
            name='protein',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='addingridient',
            name='sodium',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='addingridient',
            name='sugars',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='addrecipe',
            name='quantity',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='addrecipe',
            name='quantity_help',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='addrecipe',
            name='sub_name',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
