# Generated by Django 4.2.3 on 2023-08-22 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer_engine', '0029_alter_addingridient_calories_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='addingridient',
            name='quantity_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='addrecipe',
            name='health_condition',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='addrecipe',
            name='quantity_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='addrecipe',
            name='type_of_food',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='addrecipe',
            name='type_of_meal',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
