# Generated by Django 4.2.3 on 2023-08-25 15:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer_engine', '0033_dailyrecipe'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Launch',
            new_name='Lunch',
        ),
    ]
