# Generated by Django 4.2.3 on 2023-09-07 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer_engine', '0038_rename_usable_cals_breakfast_aa_factor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='calorycount',
            name='dish',
            field=models.IntegerField(null=True),
        ),
    ]
