# Generated by Django 4.2.3 on 2023-09-07 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer_engine', '0039_calorycount_dish'),
    ]

    operations = [
        migrations.AddField(
            model_name='calorycount',
            name='dish_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
